server:
  port: 9090
spring:
  config:
    name: priority-kafka-consumer-app

  # Kafka
  kafka:
    bootstrap-servers: ${$BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
      request.timeout.ms: 360000
    listener:
      ack-mode: manual
    consumer:
      group-id: "group-id"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false
      client-id: ${random.long}
      max-poll-records: 1000
    producer:
      batch-size: 1000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        linger.ms: 0
        enable.idempotence: false

management:
  metrics:
    tags:
      application: ${spring.config.name:default-app-name}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true

logging.level:
  root: INFO
  com.github.edn: INFO
  software.amazon.awssdk: DEBUG
  software.amazon.awssdk.request: DEBUG
  io.netty.handler.logging: DEBUG
  io.netty.handler.codec.http2.Http2FrameLogger: DEBUG